global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus самомониторинг
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - системные метрики
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  # cAdvisor - метрики контейнеров
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # MongoDB метрики
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb_exporter:9216']

  # Redis метрики
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  # FOK Bot приложение
  - job_name: 'fok_bot'
    static_configs:
      - targets: ['bot:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Celery метрики
  - job_name: 'celery'
    static_configs:
      - targets: ['celery_worker:9540']
    metrics_path: '/metrics'

  # Nginx метрики
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']