global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'fok-bot'
    replica: 'prometheus-1'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # MongoDB Exporter
  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  # Bot Application Metrics
  - job_name: 'fok-bot'
    static_configs:
      - targets: ['bot:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Bot Application Health
  - job_name: 'fok-bot-health'
    static_configs:
      - targets: ['bot:8000']
    metrics_path: '/health'
    scrape_interval: 10s

  # Celery Worker Metrics
  - job_name: 'celery-worker'
    static_configs:
      - targets: ['celery_worker:9540']
    metrics_path: '/metrics'

  # Load Balancer Metrics (HAProxy)
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8404']
    metrics_path: '/stats/prometheus'