name: SSL Certificate Renewal

on:
  schedule:
    # Run every Monday at 2 AM UTC
    - cron: '0 2 * * 1'
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain to renew certificate for'
        required: true
        default: 'your-domain.com'
      email:
        description: 'Email for Let\'s Encrypt'
        required: true
        default: 'admin@your-domain.com'

env:
  PYTHON_VERSION: '3.11'

jobs:
  renew-ssl:
    name: Renew SSL Certificates
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y certbot nginx
    
    - name: Check certificate expiry
      run: |
        python scripts/ssl_manager.py \
          --domain ${{ github.event.inputs.domain || 'your-domain.com' }} \
          --email ${{ github.event.inputs.email || 'admin@your-domain.com' }} \
          --check
    
    - name: Renew certificate if needed
      run: |
        python scripts/ssl_manager.py \
          --domain ${{ github.event.inputs.domain || 'your-domain.com' }} \
          --email ${{ github.event.inputs.email || 'admin@your-domain.com' }} \
          --renew
    
    - name: Notify renewal status
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#ssl-monitoring'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      if: always()